authentication.otp.threshold=300000
server.port=8696
jwt.secret=adc60a05cf0cf8b3a50c4c746cc1b075c1d8a091fd85d9f9e1cce592994c9f6b
jwt.expiration=604800000
itl.secret-key=vwU4YNuAbEnsbr74AbHiManYu2v5v6Ov
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://fleet-asia-test.cjuaasqwq5s9.ap-south-1.rds.amazonaws.com:5432/auth
spring.datasource.username=postgres
spring.datasource.password=Hexsenselabs020_*

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


#msg91
sixsense.messenger.url = https://control.msg91.com/api/v5/
sixsense.messenger.authKey = 395839Aw68IvfN6m1644fcd99P1
sixsense.messenger.otpMessageTemplateId = 6517dddfd6fc05269e46e212
sixsense.messenger.emailTemplateId = global_otp
sixsense.messenger.domain = mail.sixsensemobility.com
sixsense.messenger.email = SSM-Gatekeeper@mail.sixsensemobility.com


#tysis
tysis.url = https://preprod.taisys.in
tysis.client_id = n5I4RItKz1E97es0dDMagJAEF
tysis.client_secret = dtZnG-6rGeY-e4482-DhC9K-ilcBl